name: xnap-project
channels:
- pytorch
- defaults
dependencies:
- python=3.8
- pytorch=1.10.1
- torchvision
- numpy
- tqdm
- tensorboard
- protobuf<=3.20
- pip
- pandas
- pip:
  - onnx
  - wandb
  - matplotlib
  - onnxruntime
  - ipykernel
  - pillow
  - fasttext
  - einops
  - transformers
  - scikit-learn
  - seaborn